### ISSUE TITLE
Ordered lists

### ISSUE THREAD

**Issue by kaushalmodi** [chaseadamsio/goorgeous#18]
The [org spec][1] allows fine-tuning ordered lists:

- Allow list number to be anything the user wants using syntax like `[@10]`. This would be a nice-to-have support.

But more than that, it will be useful to support unordered lists nested in ordered lists and vice-versa.

```
** Ordered Lists
Ordered list items start with a numeral followed by either a period or a right parenthesis, such as =1.= or =1)=. If you want a list to start with a different value (e.g., 20), start the text of the item with =[@20]=.
#+BEGIN_SRC text
​* Lord of the Rings
My favorite scenes are (in this order)
1. The attack of the Rohirrim
2. Eowyn's fight with the witch king
   + this was already my favorite scene in the book
   + I really like Miranda Otto.
3. [@10] I just randomly want this list number to be 10.
But in the end, no individual scenes matter but the film as a whole.
#+END_SRC
*** Lord of the Rings
My favorite scenes are (in this order)
1. The attack of the Rohirrim
2. Eowyn's fight with the witch king
   + this was already my favorite scene in the book
   + I really like Miranda Otto.
3. [@10] I just randomly want this list number to be 10.
But in the end, no individual scenes matter but the film as a whole.
```

Ignoring the section numbers and CSS theme, this is how the org to html export looks:

![image](https://cloud.githubusercontent.com/assets/3578197/23031119/dcf7d73e-f43d-11e6-884f-a0e14865fe91.png)

Here is the HTML code for the list section:

```html
<div class="outline-text-4" id="text-3-2-1">
    <p>
        My favorite scenes are (in this order)
    </p>
    <ol class="org-ol">
        <li>The attack of the Rohirrim</li>
        <li>Eowyn&rsquo;s fight with the witch king
            <ul class="org-ul">
                <li>this was already my favorite scene in the book</li>
                <li>I really like Miranda Otto.</li>
            </ul>
        </li>
        <li value="10">I just randomly want this list number to be 10.</li>
    </ol>
    <p>
        But in the end, no individual scenes matter but the film as a whole.
    </p>
</div>
```

[1]: http://orgmode.org/manual/Plain-lists.html#Plain-lists

**Comment by chaseadamsio** [comment]
Sounds like there are two parts to this issue:
- [ ] support user defined values (fixed in #20)
- [ ] support nested lists (this one I've known I needed to do and it'll be a big win when it's done)

**Comment by chaseadamsio** [comment]
@kaushalmodi the value part has been implemented, please take a look!

**Comment by kaushalmodi** [comment]
Thanks! I confirm the user-defined values feature. You are on a roll! :+1:

**Comment by chaseadamsio** [comment]
@kaushalmodi, just a heads up, niklasfasching/go-org doesn't support this.

I had a branch I was getting ready to PR into Hugo this week that fixed this, but since Hugo is using a new org parser, I'm closing all the issues here, deprecating and archiving goorgeous.
