### ISSUE TITLE
Title-casing of keys

### ISSUE THREAD

**Issue by moorereason** [chaseadamsio/goorgeous#21]
I don't know org-mode, but a question related to Hugo:

Given a frontmatter of `#+title: foo`, goorgeous returns:

```go
map[string]interface{}{"Title": "foo"}
```
The other frontmatter parsers in Hugo leave the key casing as-is.  Is it necessary for the string to be title-cased?

**Comment by chaseadamsio** [comment]
Nope, not necessary. PR is opened against it, should be merged in the next 10-15 min.

**Comment by chaseadamsio** [comment]
@moorereason feel free to test locally by running `govendor update github.com/chaseadamsio/goorgeous` to get latest master. I'll do a PR to Hugo at the end of the week to update the goorgeous dependency with a batch of patches.
