### ISSUE TITLE
Newline should not create a new HTML paragraph

### ISSUE THREAD

**Issue by kaushalmodi** [chaseadamsio/goorgeous#26]
The paragraph marking style in org is the same as in markdown.

If I have 

```
abcd
efgh

ijkl
mnop
```

it should export to HTML as

```html
<p>
abcd
efgh
</p>

<p>
ijkl
mnop
</p>
```

But instead, it is currently creating a paragraph for each new line.

---

This is the expected behavior:

- A single newline does not end a paragraph.
- Two or more consecutive newlines end a paragraph (basically one ore more blank lines).

--- 

I found this issue because I like to enable `auto-fill-mode` for my posts with `fill-column` set to 70 in emacs.

**Comment by gour** [comment]
Any progress on this?

Having support for e.g. writing content in Hugo static-site-generator using org-mode support is great, but this issue is showstopper atm. 😢

**Comment by chaseadamsio** [comment]
@gour yep, I'm working on it this week. Sorry, I've had a crazy March (travel for work and moving house) and this week is the first week I've had to even get on the computer outside of working hours. PR coming.

**Comment by gour** [comment]
@chaseadamsio  Np. Let me, however, say that ability to use straight org-mode markup when writing content in Hugo is one of the strong reasony why I'm migrating to Hugo (from python-powered ssg)...and, yes, I plan to start learning Go in order to be able to contribute somehow...

**Comment by chaseadamsio** [comment]
If you have any test cases you'd like to add, please comment on #34 with cases. The PR should resolve this issue.
