### ISSUE TITLE
Add support for "smart" quotes

### ISSUE THREAD

**Issue by jackbaty** [chaseadamsio/goorgeous#28]
I would love it if setting the following in the front matter of an org file for a Hugo post would cause the output to use "smart" quotes.

`#+OPTIONS: ':t`

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
