### ISSUE TITLE
Support for VERSE block

### ISSUE THREAD

**Issue by priyadarshan** [chaseadamsio/goorgeous#29]
Hello,

Now that Goorgeous is available via Hugo, a non-profit I have been helping is considering switching to Hugo.

They curate a pretty large site offering several thousands books, all using org-syntax.

Many are poetry books, and use the [VERSE](http://orgmode.org/manual/Paragraphs.html) block.

```
#+BEGIN_VERSE
Earth’s cry ascends,
But before it touches Heaven’s Eye,
 It returns.
#+END_VERSE
```

It would be excellent for us if Goorgeous could support VERSE block.

Thank you for Goorgeous.

**Comment by chaseadamsio** [comment]
Can you share an example of the expected html block?

**Comment by priyadarshan** [comment]
This is how Emacs natively exports the block in example (Emacs 25.2.1):

```
<p class="verse">
Earth’s cry ascends,<br  />
But before it touches Heaven’s Eye,<br  />
 It returns.<br  />
</p>
```

It would be important to preserve the verse indentation, and the <p class="verse"> that allows styling.

Thank you so much for considering it.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.

**Comment by priyadarshan** [comment]
Thank you so much for all the work you put into goorgeous. It made a difference in my life and my work, and I am very grateful for that. Best of luck for all your current and future endeavours.

**Comment by curiouslychase** [comment]
Thanks @priyadarshan, that means a lot! I think @niklasfasching's implementation will support your use case a lot better, so hopefully that's helpful!
