### ISSUE TITLE
Support #+SETUPFILE:

### ISSUE THREAD

**Issue by yssource** [chaseadamsio/goorgeous#30]
I got this idea from https://github.com/fniessen/org-html-themes

![image](https://cloud.githubusercontent.com/assets/3756334/23661057/6df1c9dc-0386-11e7-89dd-5ec405098a6b.png)

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
