### ISSUE TITLE
Support #+INCLUDE:

### ISSUE THREAD

**Issue by yssource** [chaseadamsio/goorgeous#31]
I think It would be very useful to have this supported.

**Comment by yssource** [comment]
It would be much appreciated, if more org-mode syntax are going to be supported.
1. #+HTML_HEAD: 
`#+HTML_HEAD: <link href="css/style.css" rel="stylesheet" type="text/css" />`
2. {{{ macro(args) }}}

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
