### ISSUE TITLE
Table of contents is missing

### ISSUE THREAD

**Issue by bshankar** [chaseadamsio/goorgeous#41]
when I export a web page that I wrote in org-mode using hugo. The table of contents is getting generated properly when I use markdown instead. 

See
https://discuss.gohugo.io/t/table-of-contents-for-org-mode-is-empty/6272

**Comment by elbaulp** [comment]
Any progress on this? I just switched from markdow to org-mode in hugo and realized the same thing, there is no TOC. 

I don't know go, but I you give me some hints may be I can help you resolve this bug.

I suppose the way the TOC is generated must be similar to markdow, isn't? Could I just read the code that generate the markdown TOC and try to translate it to org-mode?

**Comment by chaseadamsio** [comment]
No progress, but I'll look at it this week and see if I can give some guidance.

**Comment by elbaulp** [comment]
Thanks.

**Comment by chaseadamsio** [comment]
looking at it this morning, it looks like it'll require some changes in the `Org` renderer method. 

Something like firstpass and secondpass needs to be implemented similar to how [russross/blackfriday](https://github.com/russross/blackfriday/blob/067529f716f4c3f5e37c8c95ddd59df1007290ae/markdown.go#L388). It will take a little bit of time but if I can find a good window to hammer away at it I can probably get it knocked out in an hour. 

Will update when I get started on it. If someone else wants to take a pass at it, feel free to call dibs here so we're not duplicating effort.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
