### ISSUE TITLE
Support for symbols like ndash and mdash

### ISSUE THREAD

**Issue by duckdodger** [chaseadamsio/goorgeous#46]
Org supports ndash `--` and mdash `---` which are exported properly to – and — respectively through HTML with` &ndash;` and `&mdash;`. It doesn't look like it's done in goorgeous, hence this issue. You can have a look at http://orgmode.org/worg/org-symbols.html as reference for all such special characters.

Thanks for this package, by the way! I love it. :)

**Comment by priyadarshan** [comment]
Yes, EnDash, `--`, and EmDash, `---` are quite important in humanities publications and their sites.

Org via Emacs will render EmDash, `---`,

```
It is only a question of years --- and certainly not centuries --- before its golden glint falls on the face of every nation.
```
thus:
```
<p>
It is only a question of years &#x2014; and certainly not centuries &#x2014; before its golden glint falls on the face of every nation.
</p>
```

EnDash, `--`,

```
The Supreme Court voted 5--4 to uphold the decision.
```
is rendered as,

```
<p>
The Supreme Court voted 5&#x2013;4 to uphold the decision.
</p>
```

In summary:

EmDash: `---` is rendered as ` &#x2014; `
EnDash: `--` is rendered as `&#x2013;`

**Comment by vxcamiloxv** [comment]
This is really necesary and basic

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
