### ISSUE TITLE
Consecutive ~code~ wrapped text gets joined some times

### ISSUE THREAD

**Issue by whirm** [chaseadamsio/goorgeous#47]
This:
```

either ~this~
 or  ~that~ foo.

```
will get exported to:

![untitled](https://cloud.githubusercontent.com/assets/529494/25627978/c3bb4816-2f64-11e7-83d3-045393535911.png)

I'm using goorgeous through hugo.
Thanks!

**Comment by mateusfccp** [comment]
I am having this time problem, and it's preventing me from using Org with Hugo.
Anyway, did the project died?

**Comment by chaseadamsio** [comment]
@mateusfccp it didn't die, but I slacked and I'm really sorry about that! That being said, I overhauled goorgeous (will open the PR to Hugo soon) and this is now supported correctly.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
