### ISSUE TITLE
Links on a numbered list are rendered literally

### ISSUE THREAD

**Issue by whirm** [chaseadamsio/goorgeous#48]
```

1. [[https://example.com][this is a test]]

```

renders to this:

![untitled](https://cloud.githubusercontent.com/assets/529494/25650374/b6679fca-2fdc-11e7-8b7d-4e4fe4770593.png)

I'm using goorgeous through hugo.
Thanks!

**Comment by mgmart** [comment]
First of all thank you very much for providing goorgeus. 😄 

Have the same problem with footnotes:

```[fn:1] Footnotetext [[https://example.com][LinkTitle]]```

is rendered to:

1.  Footnotetext [[https://example.com][LinkTitle]] ↩

Seems to be the same issue. Also a Hugo user.

**Comment by whirm** [comment]
Thanks!
