### ISSUE TITLE
Code beginning with a dot is not rendered as code

### ISSUE THREAD

**Issue by mgmart** [chaseadamsio/goorgeous#54]
```
   =.emacs.d= and ~.emacs.d~ are not rendered as expected.
   But =emacs.d= and ~emacs.d~ are.
```

is rendered as

<img width="323" alt="deployment_of_a_hugo_site_on_github_pages_ _pragmatic" src="https://user-images.githubusercontent.com/3919652/27814964-c9335ade-6080-11e7-9eb6-dfe08aaf01db.png">

**Comment by chaseadamsio** [comment]
Thanks @ageekymonk for fixing this.
