### ISSUE TITLE
exporting images in org mode

### ISSUE THREAD

**Issue by amosbird** [chaseadamsio/goorgeous#62]
Hello, I'm writing hugo blogs using org-mode. When inserting an image link like [[/home/amos/Pictures/Screenshots/img-2017-09-11-165647.png]], hugo doesn't export the image.

**Comment by dingesista** [comment]
I put images in the static/img folder 

and then link them in my posts like below - in a sub directory "post":

[[file:/img/post/sample.jpg]]

Hope this helps.

**Comment by amosbird** [comment]
hmm, can i make it auto exporting to the static directory? Changing path to that will break org mode's preview

**Comment by chaseadamsio** [comment]
I think this would be more of an upstream Hugo ask than a goorgeous feature. All goorgeous is doing is rendering your paths. Generally in Hugo you have a separate static files directory _in_ your repo.
