### ISSUE TITLE
Customize emphasis exportation

### ISSUE THREAD

**Issue by amosbird** [chaseadamsio/goorgeous#63]
Hi, I've defined `     (strike-through . "<strong style=\"color : red;\">%s</strong>") ` in emacs so that strike-through gets exported as red bold text. I wonder if there is a way to do that in goorgeous.

**Comment by chaseadamsio** [comment]
goorgeous currently renders your org files the way blackfriday renders markdown. It's agnostic of style since it's content specific and the styling is done through your stylesheets definitions.
