### ISSUE TITLE
multiline paragraphs with emphasis within quotes

### ISSUE THREAD

**Issue by gour** [chaseadamsio/goorgeous#68]
Do I miss something, but I do experience similar/same problem with e.g.:

In #64 the problem was solved for footnotes, but it still does exist for quotes:

```
#+BEGIN_QUOTE
Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. *It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum.*
#+END_QUOTE
```

renders as: 
![quote-shot](https://user-images.githubusercontent.com/114592/31574942-36d717ec-b0db-11e7-923b-ab08acbe7139.png)

**Comment by chaseadamsio** [comment]
The commit likely needs to be updated in the Hugo vendor json. Will check when I get a chance today and PR if that's the case.

**Comment by chaseadamsio** [comment]
Sorry for the delay, I tested ` (org-html-export-as-html)` with this block quote and org-mode itself doesn't support block quotes with inner element parsing: 

```
<blockquote>
<p>
Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. *It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum.*
</p>
</blockquote>
```

It should be possible for goorgeous to check for a parameter on the block like "render-inner" or something so that it knows to render the inner elements. How does that sound?

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
