### ISSUE TITLE
v2 should work with Blackfriday v2

### ISSUE THREAD

**Issue by bep** [chaseadamsio/goorgeous#71]
Your v2 tag still uses the old API, i.e.`blackfriday.HtmlRenderer` vs the new `blackfriday.HTMLRenderer` etc.

Probably not related, but you seem to use a very old version of Go Dep. They changed to a TOML file format a year ago.

**Comment by chaseadamsio** [comment]
Thanks @bep, I'll look at it. I haven't used dep mgmt in go other than glide, but I thought I followed the docs. Sorry about that.

**Comment by chaseadamsio** [comment]
Just an update, turns out I was using `godep` (https://github.com/tools/godep#how-to-use-godep-with-a-new-project) and not `go dep` (https://github.com/golang/dep). Updating now, will continue with changes tonight hopefully.

**Comment by chaseadamsio** [comment]
Looking into it some this morning, this pkg really did do a major version change, looks like all of the public render methods are now private, so I'm going to have to figure out a way around that, but it'll def. be a blocker for moving to blackfriday v2.0.0.

**Comment by bep** [comment]
They have basically one `RenderNode` method node, but you can type switch on the types. Maybe get some inspiration here:

https://github.com/Ambrevar/blackfriday-latex

**Comment by chaseadamsio** [comment]
👍 just saw that as I was looking at how they're doing it. It'll still take some time, but that def. makes it better (and probably a better API anyways).

**Comment by bep** [comment]
No rush. I'm struggling with exactly the same trying to get Hugo over to the new API. The goorgeous import is just one of many temporary commented out sections ... When people open up an issue about "Hugo should update to Blackfriday v2" I suspect they think the amount of work is changing some import statement.

**Comment by QuLogic** [comment]
So it's been about a year, but I don't see any more recent commits?

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
