### ISSUE TITLE
Support for #+ATTR_HTML

### ISSUE THREAD

**Issue by Ealhad** [chaseadamsio/goorgeous#72]
In `org-mode`, the `#+ATTR_HTML` syntax is used to specify attributes for the next block.

Example:
```emacs
#+ATTR_HTML: :class goorgeous
I like Rust better.
```
gives
```html
<p class="goorgeous">
I like Rust better.
</p>
```

You can have multiple lines, and multiples attributes per line, like so:
```emacs
#+ATTR_HTML: :alt Go is fine though.
#+ATTR_HTML: :width 300 :style border:2px solid black;
[[file:https://golang.org/doc/gopher/pkg.png]]
```

This is probably easier to implement than #19 (although both would be useful).
<sub>Also, thank you! Support for `org-mode` made me switch to Hugo ;)</sub>

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
