### ISSUE TITLE
Recognize =code=--- as code plus dash...

### ISSUE THREAD

**Issue by mdorman** [chaseadamsio/goorgeous#77]
`=code=---` should render as something like `<code>code</code>---`.  With the current goorgeous, the `=` signs aren't parsed, and it is simply rendered verbatim.

Still, it's a minor thing versus a very nice library.

**Comment by wd** [comment]
I think you should leave a blank before and after the `=` sign, like `*bold*, /italic/, _underlined_, =verbatim= and ~code~ `.

**Comment by chaseadamsio** [comment]
@mdorman, sorry this is a super late response. I'm refactoring goorgeous to handle stuff a little easier, 
is this sufficient?

org test:
```
this should be a code element followed by dashes: =code=---
```
out: 
```
this should be a code element followed by dashes: <code>code</code>&mdash;
```

If so, this is the  current branch that I'm working on supports this. @wd, I did a test on ` (org-html-export-as-html)` and this is the behavior org-mode has.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
