### ISSUE TITLE
/…/ at beginning of line not recognised

### ISSUE THREAD

**Issue by eadmund** [chaseadamsio/goorgeous#78]
Example:

```
/italics/
```

renders as _italics/_

And:

```
Text
/italics/
```

Renders as Text /italics/.

**Comment by polothy** [comment]
I just ran into this as well, slightly different use case:
* This: `blaw blaw blaw /italics/:\n`
* Rendered as: `blaw blaw blaw /italics/:\n` (EG: didn't render)

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
