### ISSUE TITLE
Adding a note about goorgeous in https://orgmode.org/worg/ ?

### ISSUE THREAD

**Issue by bzg** [chaseadamsio/goorgeous#83]
Hi, goorgeous looks very nice.

Worg is a community-driven documentation for anything related to org-mode.

Would you register a user on https://code.orgmode.org and mention goorgeous in worg.git?

Thanks!

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
