### ISSUE TITLE
Paragraphs that are not followed by an empty line are not parsed correctly

### ISSUE THREAD

**Issue by sometimesfood** [chaseadamsio/goorgeous#84]
When a paragraph is not followed by an empty line, it is incorrectly moved to the following section by goorgeous.

This org snippet illustrates the problem:
```
* Foo
Foo paragraph.
* Bar
Bar paragraph.
```

Expected result: The snippet above should result in the following output:
```html
<h1 id="foo">Foo</h1>

<p>Foo paragraph.</p>

<h1 id="bar">Bar</h1>

<p>Bar paragraph.</p>
```

Actual result: The snippet above results in the following output:
```html
<h1 id="foo">Foo</h1>

<h1 id="bar">Bar</h1>

<p>Foo paragraph.
Bar paragraph.</p>
```

While empty-line paragraph style seems to be preferred in the org-mode community, org.el renders the example above correctly. Also, the [org syntax reference](https://orgmode.org/worg/dev/org-syntax.html#org8301db0) states that "[e]mpty lines and other elements end paragraphs".

Here's a branch that adds a (failing) test case for this issue:
https://github.com/sometimesfood/goorgeous/tree/linebreak-fail
https://github.com/sometimesfood/goorgeous/commit/8cc4f08b45d3e7fd0820efb386d65419d9114681

**Comment by sometimesfood** [comment]
Just for reference: This seems to have been broken by commit 95384d4f9d9d06abe2788aa43c91473ef9c52a68.

**Comment by 0pendev** [comment]
Faced the same error when using gitea. 
Would be nice to find a way to resolve it.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
