### ISSUE TITLE
Multiple hyphens not converted to dashes

### ISSUE THREAD

**Issue by soldeace** [chaseadamsio/goorgeous#86]
Ideally, the double hyphen (--) should be rendered as en dash (–), and triple hyphen (---) as em dash (—), just like org-mode already does when exporting to HTML ([source](https://orgmode.org/manual/Special-symbols.html)).

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
