### ISSUE TITLE
Markup in footnotes is rendered literally

### ISSUE THREAD

**Issue by soldeace** [chaseadamsio/goorgeous#87]
Bold, italic, links, and whatnot are rendered literally if inside a footnote. Example:

![captura de tela de 2018-05-26 13-11-36](https://user-images.githubusercontent.com/5541244/40578199-71d88b44-60e6-11e8-992a-c4409fe7434b.png)

I'm using Goorgeous with Hugo.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
