### ISSUE TITLE
Complete Hugo Taxonomies support

### ISSUE THREAD

**Issue by MunifTanjim** [chaseadamsio/goorgeous#88]
Currently only the default taxonomies: `tags` and `categories` are hardcoded:

https://github.com/chaseadamsio/goorgeous/blob/dcf1ef873b8987bf12596fe6951c48347986eb2f/header.go#L56

But if Hugo site has other taxonomies, `goorgeous` can't parse them from the `.org` file headers.

Any way to support those?

---

I don't know if Org-mode syntax supports list in headers variables (which start with `#+`). If it does, then supporting that should solve this problem.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week that fixed this, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
