### ISSUE TITLE
src blocks only render in caps

### ISSUE THREAD

**Issue by glallen01** [chaseadamsio/goorgeous#92]
This renders fine:
```
#+BEGIN_SRC bash
  #!/bin/bash
  uname -a
#+END_SRC
```

This does not, 
```
#+begin_src bash
  #!/bin/bash
  uname -a
#+end_src
```
however lower-case is the default when using `C-c C-,` rather than `<s TAB` in the new 9.2.2 org-mode.

**Comment by chaseadamsio** [comment]
I had a branch I was getting ready to PR into Hugo this week, but it looks like @niklasfasching PR'ed a new org parser, so I'm closing all the issues here, deprecating and archiving goorgeous.
